name: Release Docker Image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag and lowercase repo
        id: meta
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          repo_lower=$(echo "${GITHUB_REPOSITORY,,}")
          echo "repo=${repo_lower}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}
