name: Semantic release

on:
  push:
    branches: 
    - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release:
    uses: GEWIS/actions/.github/workflows/docker-release.yml@v1
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: "['.']"
      version: ${{ needs.versioning.outputs.next-version }}
      github-registry: "true"

